# Generated by Django 2.1.8 on 2019-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
