# Generated by Django 2.1.8 on 2019-04-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190401_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='todo',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
