# Generated by Django 2.1.8 on 2019-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190401_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='completed',
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_completion_date',
            field=models.DateField(null=True),
        ),
    ]
