# Generated by Django 2.1.8 on 2019-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20190401_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='target_completion_date',
            field=models.DateField(blank=True),
        ),
    ]
