# Generated by Django 2.1.8 on 2019-04-06 11:59

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_todo_completed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
