# Generated by Django 2.2 on 2019-04-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_todo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
